#!/usr/bin/env bash

FILE=`realpath $1`
EXTRACT_DIR=$2

# Set constants used when calculating payloads
FOOTER_SIZE=52

FILE_SIZE=`stat --format "%s" "$FILE"`
offset=$(($FILE_SIZE - 4))

MAGIC_OFFSET=$offset
offset=$(($offset - 4))

CHECKSUM_OFFSET=$offset
offset=$(($offset - 4))

VERSION_OFFSET=$offset
offset=$(($offset - 4))

PREPAYLOAD_OFFSET=$offset
offset=$(($offset - 4))

PREPAYLOAD_SIZE_OFFSET=$offset
offset=$(($offset - 4))

LAUNCHER_SIZE_OFFSET=$offset
offset=$(($offset - 4))

PAYLOAD_OFFSET=$offset
offset=$(($offset - 4))

PAYLOAD_SIZE_OFFSET=$offset
offset=$(($offset - 4))

set_lengths() {
    LAUNCHER_SIZE=`od -An -t u4 -N 4 -j $LAUNCHER_SIZE_OFFSET "$FILE" | tr -d ' '`
    PAYLOAD_SIZE=`od -An -t u4 -N 4 -j $PAYLOAD_SIZE_OFFSET "$FILE" | tr -d ' '`
    PREPAYLOAD_SIZE=`od -An -t u4 -N 4 -j $PREPAYLOAD_SIZE_OFFSET "$FILE" | tr -d ' '`
    SKIP_BYTES=$(($PREPAYLOAD_SIZE + $LAUNCHER_SIZE))
    return 0
}

extract_installer() {
    mkdir -p "$EXTRACT_DIR"/installer

    echo -n "Extracting VMware installer..."

    (dd if="$FILE" ibs=$SKIP_BYTES obs=1024 skip=1 | gunzip -c | tar -xf - -C "$EXTRACT_DIR"/installer)

    if [ ! -e "$bootstrapper" ]; then
        echo "done."
    fi
}

extract_prepayload() {
    mkdir -p "$EXTRACT_DIR"/prepayload

    echo -n "Extracting VMware pre-payload..."

    (dd if="$FILE" ibs=$LAUNCHER_SIZE obs=1024 skip=1 | gunzip -c | tar -xf - -C "$EXTRACT_DIR"/prepayload)
}

echo "Extracting: $FILE"
set_lengths
extract_installer
extract_prepayload
